pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
		    echo ".....Archieve Successful....."
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
	    	echo ".....Starting deployment....."
		if (build job: 'deploy_application_staging_env2')
		then
			echo "...deployment to stage env successful..."
		else
			echo "...deployment to stage env failed..."
            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'deploy_application_prod_env'
            }
        }
    }
}
