pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
		    echo ".....Archieve Successful....."
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
	    	echo ".....Starting deployment....."
		build job: 'Deploy_application_staging_env'
		echo "...deployment to stage env successful..."
            }
            
        }
        stage('Deploy to Production'){
            steps{
	    	echo "...Inside prod deployment..."
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy_application_prod_env'
            }
        }
    }
}
